# Generated by Django 2.2 on 2023-02-23 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
                ('time_create', models.DateTimeField(default=datetime.datetime(2023, 2, 24, 1, 10, 40, 800920))),
            ],
        ),
    ]
